Reporting/Controllers/ReportingController.cs
using Reporting.Models;
using Reporting.Models.Entities;
using Reporting.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Reporting.Controllers
{
    public class ReportingController : Controller
    {
        // GET: Reporting
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListTransaction(ListViewModel filter)
        {
            //call the reporting Model
            ReportingModel reportingModel = new ReportingModel();
            //call the function inside the model
            IEnumerable<tPurchaseOrder> transactionList = reportingModel.ListTransaction(filter);
            //instance of ListViewModel
            filter.TransactionList = transactionList;
            //return the list
            return View(filter);
        }
    }
}

Reporting/Views/Reporting/Index.cshtml
@model Reporting.ViewModels.ListViewModel

@{
    ViewBag.Title = "Index";
}

<h2 align="center">DoTransactionHistory</h2>
<h4 align="center">Tutorial 3.0 (1)</h4>

<table class="table">
    <tr>
        <td><p>Search For Date</p></td>
    </tr>
    <tr>

        <div class="form-group">
            <td>@Html.LabelFor(model => model.TransactionHistory.TransferDate)</td>
            <td>@Html.TextBoxFor(model => model.TransactionHistory.TransferDate, new { htmlAttributes = new { @class = "form-control" } })</td>
            <td>@Html.LabelFor(model => model.TransactionHistory.TransferDate)</td>
            <td>@Html.TextBoxFor(model => model.TransactionHistory.TransferDate, new { htmlAttributes = new { @class = "form-control" } })</td>
            <td>@Html.LabelFor(model => model.TransactionHistory.TransferDate)</td>
            <td>@Html.TextBoxFor(model => model.TransactionHistory.TransferDate, new { htmlAttributes = new { @class = "form-control" } })</td>
        </div>

    <tr>
        <td><p>Search For Company ID</p></td>
    </tr>
    <tr>
        <td>
            <div class="form-group">
                @Html.LabelFor(model => model.TransactionHistory.CompanyRemID)
                @Html.TextBoxFor(model => model.TransactionHistory.CompanyRemID, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </td>
    </tr>
    <tr>
        <td><p>Search For Rem ID</p></td>
    </tr>
    <tr>
        <td>
            <div class="form-group">
                @Html.LabelFor(model => model.TransactionHistory.RemID)
                @Html.TextBoxFor(model => model.TransactionHistory.RemID, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </td>
    </tr>
    <tr>
        <td><p>Search For Cart ID</p></td>
    </tr>
    <tr>
    <td>
        <div class="form-group">
            @Html.LabelFor(model => model.TransactionHistory.CartID)
            @Html.TextBoxFor(model => model.TransactionHistory.CartID, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </td>
    </tr>
    <tr>
        <td><p>Search For Status</p></td>
    </tr>
    <tr>
        <td>
            <div class="form-group">
                @Html.LabelFor(model => model.TransactionHistory.Status)
                @Html.TextBoxFor(model => model.TransactionHistory.Status, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </td>
    </tr>
    <tr>
        <td><p>Search For Payment Gateway</p></td>
    </tr>
    <tr>
        <td>
            <div class="form-group">
                @Html.LabelFor(model => model.TransactionHistory.Method)
                @Html.TextBoxFor(model => model.TransactionHistory.Method, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </td>
    </tr>
    <tr>
        <td align="right"><button type="submit" class="btn btn-default">Search</button></td>
    </tr>
</table>
<h4>List of Transaction History</h4>
<table class="table">
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.CompanyRemID)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.TransferDate)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.RemID)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.CartID)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.TransferCurrency)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.TransferAmount)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.Method)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.Status)</b></td>

    </tr>
        <tr>
            <td>@Html.DisplayFor(Model => Model.TransactionHistory.Status)</td>
        </tr>
</table>

Reporting/Views/Reporting/ListTransaction.cshtml
@model Reporting.ViewModels.ListViewModel
@{
    ViewBag.Title = "TransactionHistory";
}

<h2 align="center">DoTransactionHistory</h2>
<h4 align="center">Tutorial 3.0 (1)</h4>

<table class="table">
    @using (Html.BeginForm("ListTransaction", "Reporting", new { id = "filter" }, FormMethod.Post))
    {
        <tr>
            <td><p>Search For Date</p></td>
        </tr>
        <tr>
            <div class="form-group">
                <td>@Html.LabelFor(model => model.TransactionHistory.TransferDate)</td>
                <td>@Html.TextBoxFor(model => model.TransactionHistory.TransferDate, new { htmlAttributes = new { @class = "form-control" }, @maxlength = 10, @minlength = 10})</td>
                <td>@Html.LabelFor(model => model.TransactionHistory.TransferHour)</td>
                <td>@Html.TextBoxFor(model => model.TransactionHistory.TransferHour, new { htmlAttributes = new { @class = "form-control" }, @maxlength = 2, @minlength = 2 })</td>
                <td>@Html.LabelFor(model => model.TransactionHistory.TransferMinute)</td>
                <td>@Html.TextBoxFor(model => model.TransactionHistory.TransferMinute, new { htmlAttributes = new { @class = "form-control" }, @maxlength = 2, @minlength = 2 })</td>
            </div>
        </tr>

        <tr>
            <td><p>Search For Company ID</p></td>
        </tr>
        <tr>
            <td>
                <div class="form-group">
                    @Html.LabelFor(model => model.TransactionHistory.CompanyRemID)
                    @Html.TextBoxFor(model => model.TransactionHistory.CompanyRemID, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </td>
        </tr>
        <tr>
            <td><p>Search For Rem ID</p></td>
        </tr>
        <tr>
            <td>
                <div class="form-group">
                    @Html.LabelFor(model => model.TransactionHistory.RemID)
                    @Html.TextBoxFor(model => model.TransactionHistory.RemID, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </td>
        </tr>
        <tr>
            <td><p>Search For Cart ID</p></td>
        </tr>
        <tr>
        <td>
            <div class="form-group">
                @Html.LabelFor(model => model.TransactionHistory.CartID)
                @Html.TextBoxFor(model => model.TransactionHistory.CartID, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </td>
        </tr>
        <tr>
            <td><p>Search For Status</p></td>
        </tr>
        <tr>
            <td>
                <div class="form-group">
                    @Html.LabelFor(model => model.TransactionHistory.Status)
                    @Html.TextBoxFor(model => model.TransactionHistory.Status, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </td>
        </tr>
        <tr>
            <td><p>Search For Payment Gateway</p></td>
        </tr>
        <tr>
            <td>
                <div class="form-group">
                    @Html.LabelFor(model => model.TransactionHistory.Method)
                    @Html.TextBoxFor(model => model.TransactionHistory.Method, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </td>
        </tr>
        <tr>
            <td align="right"><button type="submit" class="btn btn-default">Search</button></td>
        </tr>
    }
    </table>
<h4>List of Transaction History</h4>
<table class="table">
    <tr>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.CompanyRemID)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.TransferDate)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.RemID)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.CartID)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.TransferCurrency)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.TransferAmount)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.Method)</b></td>
        <td><b>@Html.DisplayNameFor(model => model.TransactionHistory.Status)</b></td>

    </tr>
    @foreach (var item in Model.TransactionList)
    {
<tr>
    <td>@Html.DisplayFor(Model => item.CompanyRemID)</td>
    <td>@Html.DisplayFor(Model => item.TransferDate)</td>
    <td>@Html.DisplayFor(Model => item.RemID)</td>
    <td>@Html.DisplayFor(Model => item.CartID)</td>
    <td>@Html.DisplayFor(Model => item.TransferCurrency)</td>
    <td>@Html.DisplayFor(Model => item.TransferAmount)</td>
    <td>@Html.DisplayFor(Model => item.Method)</td>
    <td>@Html.DisplayFor(Model => item.Status)</td>
</tr>
    }

</table>