Reporting/Models/Objects/SummaryTransactions.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Reporting.Models.Objects
{
    public class SummaryTransactions
    {
        public string TotalCount { get; set; }
        public decimal? TotalAmount { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string CompanyRemID { get; set; }
        public decimal? TransferAmount { get; set; }
        public string TransferDate { get; set; }
    }
}

Reporting/ViewModels/SummaryViewModel.cs
using Reporting.Models.Entities;
using Reporting.Models.Objects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Reporting.ViewModels
{
    public class SummaryViewModel
    {
        public SummaryTransactions Summary { get; set; }
        public IEnumerable<SummaryTransactions> ListSummary { get; set; }
    }
}

Reporting/Controllers/SummaryController.cs
using Reporting.Models;
using Reporting.Models.Entities;
using Reporting.Models.Objects;
using Reporting.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Reporting.Controllers
{
    public class SummaryController : Controller
    {
        // GET: Summary
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SummaryTransactions(SummaryViewModel filter)
        {
            SummaryModel summaryModel = new SummaryModel();
            IEnumerable<SummaryTransactions> summaryList = summaryModel.SummaryTransactions(filter);
            filter.ListSummary = summaryList;
            return View(filter);
        }
    }
}

Reporting/Views/Summary/SummaryTransactions.cshtml
@model Reporting.ViewModels.SummaryViewModel
@{
    ViewBag.Title = "SummaryTransaction";
}

<h2>SummaryTransaction</h2>
<h4>Tutorial 3.0(2)</h4>

<table class="table">
    @using (Html.BeginForm("SummaryTransactions", "Summary", new { id = "filter" }, FormMethod.Post))
    {
        <tr>
            <td><p>Search For Date</p></td>
        </tr>
        <tr>
            <td>
                <div class="form-group">
                    @Html.LabelFor(model => model.Summary.Month)
                    @Html.TextBoxFor(model => model.Summary.Month, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.LabelFor(model => model.Summary.Year)
                    @Html.TextBoxFor(model => model.Summary.Year, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </td>
        </tr>
        <tr>
            <td><p>Search For Company ID</p></td>
        </tr>
        <tr>
            <td>
                <div class="form-group">
                    @Html.LabelFor(model => model.Summary.CompanyRemID)
                    @Html.TextBoxFor(model => model.Summary.CompanyRemID, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </td>
        </tr>
        <tr>
            <td align="right"><button type="submit" class="btn btn-default">Search</button></td>
        </tr>
     }
    </table>
    <h4>List of Transaction Summary</h4>
    <table class="table">
        <tr>
            <td><b>@Html.DisplayNameFor(model => model.Summary.Month)</b></td>
            <td><b>@Html.DisplayNameFor(model => model.Summary.TotalCount)</b></td>
            <td><b>@Html.DisplayNameFor(model => model.Summary.TotalAmount)</b></td>
        </tr>
        @foreach (var item in Model.ListSummary)
        {
    <tr>
        <td>@Html.DisplayFor(Model => item.Month)</td>
        <td>@Html.DisplayFor(Model => item.TotalCount)</td>
        <td>@Html.DisplayFor(Model => item.TotalAmount)</td>
    </tr>
        }
    </table>